version: "3.8"

services:
  budget:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-app
    ports:
      - "8601:8601"
    environment:
      DB_PATH: /app/data/budget_app.db
      STREAMLIT_SERVER_PORT: "8601"
      STREAMLIT_SERVER_ADDRESS: "1.1.1.1"
    volumes:
      - ./data:/app/data   # Persiste la base en local (./data)
      - ./app.py:/app/app.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    restart: unless-stopped
  nginx_:
    image: nginx:latest
    container_name: nginx_
    ports:
      - "81:81"
      - "444:444"
    depends_on:
      - budget
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d