[project]
name = "budget"
version = "0.1.0"
description = "Application gestion budget"
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "pandas",
    "plotly",
    "streamlit-extras"
]
