credentials:
  usernames:
    admin:
      email: "f.boussengui@gmail.com"
      name: "Francoisb"
      failed_login_attempts: 0
      logged_in: false
      password: "$2b$12$R3GuRfDTOKjkPl1jPMKLROtsiuxbFvymJ/RkDNIxJ/gPwg0UIgGMC"

cookie:
  expiry_days: 30
  name: "budget_app_cookie"
  key: "budget_app_key_change_in_production"

preauthorized:
  emails: []